spring:
  url:
    base: http://localhost:8080

  servlet:
    multipart: #upload File
      file-size-threshold: 1MB
      location: ./uploadFile
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: jdbc:h2:tcp://localhost:9092/mem:testdb;MODE=MySQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: classpath:datasource/schema.sql
    data: classpath:datasource/data.sql