server:
  port: 8080

spring:
  url:
    base: http://localhost:8080

  profiles:
    active: local

  logging: # Logging Configuration File Path
    config: classpath:config/logback-${spring.profiles.active}.xml

  jwt:
    secret: bigone

  social:
    kakao:
      client_id:  # 앱생성시 받은 REST API 키
      redirect: /social/login/kakao
      url:
          login: https://kauth.kakao.com/oauth/authorize
          token: https://kauth.kakao.com/oauth/token
          profile: https://kapi.kakao.com/v2/user/me

  servlet:
    multipart: #upload File
      file-size-threshold: 1MB
      location: ./uploadFile
      max-file-size: 100MB
      max-request-size: 100MB

# h2 DB Server Configuration
h2info:
  master:
    port: 8500
    db-name: testdb
    user-name: sa
    password:
    script-schema: datasource/schema.sql
    script-data: datasource/data.sql
    db-mode: MYSQL
    char-Set: utf-8

# Database Configuration
database:
  master:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:tcp://localhost:${h2info.master.port}/${h2info.master.dbname};MODE=${h2info.master.db-mode};
    username: ${h2info.master.user-name}
    password: ${h2info.master.password}



