logging:
  level:
    root: warn
    com.rest.api: info
  path: /home/ec2-user/api/log
  file:
    max-history: 7

spring:
  profiles: pord
  url:
    base: http://localhost:8080
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    properties.hibernate:
#      hbm2ddl.auto: none
#      format_sql: true
#      use_sql_comments: true
#    show_sql: true
#    generate-ddl: false
  datasource:
    url: jdbc:h2:tcp://localhost:9092/mem:testdb;
    username: sa
    password:
    driver-class-name: org.h2.Driver
