server:
  port: 8080
url:
  base: http://localhost:8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/mem:testdb;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate:
      hbm2ddl.auto: update
      format_sql: true
      use_sql_comments : true
    show_sql: true

  messages:
    basename: i18n/exception
    encoding: utf-8
  jwt:
    secret: bigone

social:
  kakao:
    client_id:  # 앱생성시 받은 REST API 키
    redirect: /social/login/kakao
    url:
      login: https://kauth.kakao.com/oauth/authorize
      token: https://kauth.kakao.com/oauth/token
      profile: https://kapi.kakao.com/v2/user/me
