server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/mem:testdb;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: none
    showSql: true